apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary
  namespace: stable-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
      track: canary
  template:
    metadata:
      labels:
        app: nodeapp
        track: canary
    spec:
      containers:
      - image: gcr.io/$PROJECT_NAME/nodeapp-canary:1.0.0
        name: app-canary
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
        resources:
          limits:
            memory: "128Mi"
            cpu: "10m"